### ISSUE TITLE
website unavailable

### ISSUE THREAD

**Issue by FND** [lemonmade/bigfoot#7]
the README's project page and demo links redirect to http://www.bigfootjs.com, but that address is currently unavailable

aside: it'd be nice if this repo's header included a link to that site

**Comment by brunob** [comment]
@lemonmade what happens to the website finally ? it seems down since a long time :\

http://www.downforeveryoneorjustme.com/http://www.bigfootjs.com/

archive.org can help https://web.archive.org/web/20150521152329/http://www.bigfootjs.com/ but it would be nice to see the website up :) what about putting it in gh-brach on this repo ?

**Comment by lemonmade** [comment]
I am working on redoing the website, at which point I will move it onto a gh-brance. I think the site is back up — weird thing with DNS that I don't understand, ha. Can you see if it's up for you, too?

**Comment by brunob** [comment]
it works ;) http://www.bigfootjs.com/
